[build]
command = "npm run build"
base = "."
publish = "_static"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
